apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/dev-Anamul/gitops-lab.git
    targetRevision: main
    path: environments/dev/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
